services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - 8888:80
    volumes:
      - ./data:/var/www/data
    # Optional: Only used for log files...
    environment:
      - TZ=${TZ}
  app:
    build:
      context: ./app
    user: 1000:1000
    volumes:
      - ./data:/data # Make sure your local directory exists
    environment:
      # Optional: Only used for log files...
      - TZ=${TZ}

      # Optional: Login credentials. If none are specified, authentication is disabled.
      - FLIMSY_USERNAME=${FLIMSY_USERNAME}
      - FLIMSY_PASSWORD=${FLIMSY_PASSWORD}

      # Optional: OpenWeatherMap.org API settings.
      - FLIMSY_WEATHER_API_KEY=${FLIMSY_WEATHER_API_KEY}
      - FLIMSY_WEATHER_LATITUDE=${FLIMSY_WEATHER_LATITUDE}
      - FLIMSY_WEATHER_LONGITUDE=${FLIMSY_WEATHER_LONGITUDE}
      - FLIMSY_WEATHER_UNITS=${FLIMSY_WEATHER_UNITS}
      - FLIMSY_WEATHER_LANGUAGE=${FLIMSY_WEATHER_LANGUAGE}

      # Optional: Name of the CPU Temp sensor in lm-sensors. Most likely "Tctl" for Ryzen CPUs or "Package id 0" for Xeon CPUs.
      - FLIMSY_CPU_TEMP_SENSOR=${FLIMSY_CPU_TEMP_SENSOR}

      # Optional: Coma separated list of storage mount points to monitor.
      - FLIMSY_MOUNT_POINTS=${FLIMSY_MOUNT_POINTS}
    develop:
      watch:
        - action: sync
          path: ./app/src
          target: /var/www
