services:
  app:
    build:
      context: .
    hostname: flimsy
    ports:
      - 8888:80
    environment:
      - FLIMSY_USERNAME=${FLIMSY_USERNAME}
      - FLIMSY_PASSWORD=${FLIMSY_PASSWORD}
      - FLIMSY_WEATHER_API_KEY=${FLIMSY_WEATHER_API_KEY}
      - FLIMSY_WEATHER_LONGITUDE=${FLIMSY_WEATHER_LONGITUDE}
      - FLIMSY_WEATHER_LATITUDE=${FLIMSY_WEATHER_LATITUDE}
      - FLIMSY_WEATHER_UNITS=${FLIMSY_WEATHER_UNITS}
      - FLIMSY_WEATHER_LANGUAGE=${FLIMSY_WEATHER_LANGUAGE}
    volumes:
      - ./data:/data
    develop:
      watch:
        - action: sync
          path: ./src
          target: /var/www/html

