services:
  app:
    container_name: flimsy
    build:
      context: .
    volumes:
      - data:/data
    environment:
      # Optional: Only used for log files...
      - TZ=${TZ:-UTC}

      # Optional: Login credentials. If none are specified, authentication is disabled.
      - FLIMSY_USERNAME=${FLIMSY_USERNAME}
      - FLIMSY_PASSWORD=${FLIMSY_PASSWORD}

      # Optional: OpenWeatherMap.org API settings.
      - FLIMSY_WEATHER_API_KEY=${FLIMSY_WEATHER_API_KEY}
      - FLIMSY_WEATHER_LOCATION=${FLIMSY_WEATHER_LOCATION}
      - FLIMSY_WEATHER_UNITS=${FLIMSY_WEATHER_UNITS}
      - FLIMSY_WEATHER_LANGUAGE=${FLIMSY_WEATHER_LANGUAGE}

      # Optional: Name of the CPU Temp sensor in lm-sensors. Most likely "Tctl" for Ryzen CPUs or "Package id 0" for Xeon CPUs.
      - FLIMSY_CPU_TEMP_SENSOR=${FLIMSY_CPU_TEMP_SENSOR}

      # Optional: Set if you want to bind to something else than 0.0.0.0:8080
      - FLIMSY_HOST=${FLIMSY_HOST}
      - FLIMSY_PORT=${FLIMSY_PORT}
    ports:
      - 8080:${FLIMSY_PORT:-8080}
volumes:
  data:
