services:
  app:
    build:
      context: .
    ports:
      - 8888:80
    environment:
      - FLIMSY_USERNAME=${FLIMSY_USERNAME}
      - FLIMSY_PASSWORD=${FLIMSY_PASSWORD}
    volumes:
      - ./data:/data
    develop:
      watch:
        - action: sync
          path: ./src
          target: /var/www/html

