services:
  app:
    build:
      context: .
    ports:
      - 8888:80
    volumes:
      - ./data:/data
    develop:
      watch:
        - action: sync
          path: ./src
          target: /var/www/html

