services:
  # web:
  #   build:
  #     context: .
  #     dockerfile: ./web/Dockerfile
  #   ports:
  #     - 8888:80
  #   volumes:
  #     - ./data:/var/www/data
  #   # Optional: Only used for log files...
  #   environment:
  #     - TZ=${TZ:-UTC}
  #   develop:
  #     watch:
  #       - action: sync
  #         path: ./app/src
  #         target: /var/www
  app:
    build:
      context: ./app
    volumes:
      - ./data:/data # Make sure your local directory exists and is owned by the user with UID 1000 
      - /home/phil/Data:/mnt/Data/:ro
      - /home/phil/OldData:/mnt/OldData/:ro
    environment:
      # Optional: Only used for log files...
      - TZ=${TZ:-UTC}

      # Optional: Login credentials. If none are specified, authentication is disabled.
      - FLIMSY_USERNAME=${FLIMSY_USERNAME}
      - FLIMSY_PASSWORD=${FLIMSY_PASSWORD}

      # Optional: OpenWeatherMap.org API settings.
      - FLIMSY_WEATHER_API_KEY=${FLIMSY_WEATHER_API_KEY}
      - FLIMSY_WEATHER_LOCATION=${FLIMSY_WEATHER_LOCATION}
      - FLIMSY_WEATHER_UNITS=${FLIMSY_WEATHER_UNITS}
      - FLIMSY_WEATHER_LANGUAGE=${FLIMSY_WEATHER_LANGUAGE}

      # Optional: Name of the CPU Temp sensor in lm-sensors. Most likely "Tctl" for Ryzen CPUs or "Package id 0" for Xeon CPUs.
      - FLIMSY_CPU_TEMP_SENSOR=${FLIMSY_CPU_TEMP_SENSOR}
    develop:
      watch:
        - action: sync
          path: ./app/src
          target: /usr/src/app
#volumes:
  #  data:
