services:
  app:
    build:
      context: .
    volumes:
      - ./data:/data # Make sure your local directory exists and is owned by the user with UID 1000 
      - /home/phil/Data:/mnt/Data/:ro
      - /home/phil/OldData:/mnt/OldData/:ro
    environment:
      # Optional: Only used for log files...
      - TZ=${TZ:-UTC}

      # Optional: Login credentials. If none are specified, authentication is disabled.
      - FLIMSY_USERNAME=${FLIMSY_USERNAME}
      - FLIMSY_PASSWORD=${FLIMSY_PASSWORD}

      # Optional: OpenWeatherMap.org API settings.
      - FLIMSY_WEATHER_API_KEY=${FLIMSY_WEATHER_API_KEY}
      - FLIMSY_WEATHER_LOCATION=${FLIMSY_WEATHER_LOCATION}
      - FLIMSY_WEATHER_UNITS=${FLIMSY_WEATHER_UNITS}
      - FLIMSY_WEATHER_LANGUAGE=${FLIMSY_WEATHER_LANGUAGE}

      # Optional: Name of the CPU Temp sensor in lm-sensors. Most likely "Tctl" for Ryzen CPUs or "Package id 0" for Xeon CPUs.
      - FLIMSY_CPU_TEMP_SENSOR=${FLIMSY_CPU_TEMP_SENSOR}
    ports:
      - 8888:8080
    develop:
      watch:
        - action: sync
          path: ./src
          target: /usr/src/flimsy
          ignore:
            - static/
            - templates/
        - action: sync
          path: ./src/static
          target: /var/lib/flimsy/static
        - action: sync
          path: ./src/templates
          target: /var/lib/flimsy/templates
#volumes:
  #  data:
