services:
  app:
    container_name: flimsy
    build:
      context: .
    volumes:
      - data:/data
    env_file: .env
    restart: unless-stopped
    ports:
      - 8080:${FLIMSY_PORT:-8080}
volumes:
  data:
