FROM alpine:latest AS builder 

RUN apk add --no-cache git go gcc
RUN apk add --no-cache lm-sensors tzdata

RUN mkdir -p /usr/src/flimsy
WORKDIR /usr/src/flimsy

RUN go install github.com/air-verse/air@latest

COPY ./src/ .

RUN go mod init github.com/BeringLogic/flimsy
RUN go mod tidy 

RUN /root/go/bin/air init

RUN mkdir /data
VOLUME /data

CMD ["/root/go/bin/air", "--build.cmd", "go build -o bin/flimsy cmd/flimsy/main.go", "--build.bin", "./bin/flimsy", "-build.stop_on_error", "true"]
