name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.io/beringlogic/flimsy:$(date +%s)

    - name: Docker Scout
      id: docker-scout
      uses: docker/scout-action@v1
      with:
        command: compare
        image: docker.io/beringlogic/flimsy:$(date +%s)
        to-env: production
        ignore-unchanged: false
        github-token: ${{ secrets.GITHUB_TOKEN }}
