name: govulncheck

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: 1.23.7
        cache: false
        check-latest: true

    - name: build
      working-directory: ./src
      run: |
        go mod init github.com/BeringLogic/flimsy
        go mod tidy
        go build ./cmd/flimsy/main.go

    - name: govulncheck
      working-directory: ./src
      run: |
        go install golang.org/x/vuln/cmd/govulncheck@latest
        govulncheck ./...
