name: govulncheck

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  govulncheck:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: 1.23.7
        cache: false
        check-latest: true

    - name: build
      working-directory: ./src
      run: |
        go mod init github.com/BeringLogic/flimsy
        go mod tidy
        go build ./cmd/flimsy/main.go

    - id: govulncheck
      uses: golang/govulncheck-action@v1
      with:
         go-version-input: 1.23.7
         work-dir: ./src
