name: govulncheck

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write # for github/codeql-action/upload-sarif to upload SARIF results

jobs:

  govulncheck:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: 1.24

    - name: build
      run: |
        go mod download
        go build ./cmd/flimsy/main.go

    - name: govulncheck
      run: |
        go install golang.org/x/vuln/cmd/govulncheck@latest
        govulncheck -format sarif ./... > govulncheck.sarif

    - name: Upload sarif to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: './govulncheck.sarif'
